### ISSUE TITLE
Add expiry for data collection

### ISSUE THREAD

**Issue by dirkjanfaber** [victronenergy/venus-influx-loader#173]
In order not to have sites collect data indefintely, an expiry column should lbe added to the table, indicating when to stop collecting data. E.g. defaulting to 3 months and having some way to get a reminder when the data collection is about to expire. Either on email, or shown somewhere on the frontend, ie VRM or Grafana.

<img width="1213" alt="image" src="https://github.com/victronenergy/venus-influx-loader/assets/3098947/40efbb7c-9bd2-4bb4-978c-3eb32de93ba1">

**Comment by mman** [comment]
Some good progress on the issue. Now you can use `--enable-auto-expiry` or `--enable-auto-expiry 21d` to nudge Influx Loader into handling the expiry... and it will show up in the UI nicely...

<img width="990" alt="Screenshot 2024-10-18 at 14 02 51" src="https://github.com/user-attachments/assets/5408a401-d449-4990-8ebf-19ca9c6237af">

... remaining functionality is to compose everything together...
