### ISSUE TITLE
Custom Grafana URL

### ISSUE THREAD

**Issue by HarmtH** [victronenergy/venus-influx-loader#186]
Hi,

With venus-grafana-deployer, Grafana isn't running [here](https://github.com/victronenergy/venus-influx-loader/blob/1.2.1/src/client/navigation.js#L60)

Can we have this location configurable, preferably via an env var?

**Comment by mman** [comment]
Definitely, good catch. Do we need to override just the `port` (meaning Grafana will be running side by side with Influx Loader) or complete `GRAFANA_URL`?

**Comment by HarmtH** [comment]
At the moment in venus-grafana-deployer, we have Grafana running on / (the root) of the same host / domain name. So I guess having the `port` configurable would be enough. But for flexibility I'd rather be able to specify the full URL if possible (which I guess can even be the relatively relative `/` in this case).
