### ISSUE TITLE
Bug: support directory path in influxdb uri and HTTPS requests to influxdb

### ISSUE THREAD

**Issue by maurerle** [victronenergy/venus-influx-loader#205]
The current implementation does not allow setting https (when port 443 is used for example to access the system).

It is also not possible to add a subdirectory path to use an influxdb hosted behind a reverse proxy in a directory location.

For example I would like to connect to my influxdb at `https://example.com:443/victron-influxdb/`.

Currently, the connection attempt to port 443 is still done using http, resulting in a 400 error due to the wrong protocol.

**Comment by mman** [comment]
Correct, thanks for filing this. It needs to be fixed.
