### ISSUE TITLE
Support for Pylontech batteries

### ISSUE THREAD

**Issue by maurerle** [victronenergy/venus-influx-loader#233]
Hi,

we just attached the Pylontech Battery plug to the Cerbo GX to also retrieve data about the SoC.
Unfortunately, this is not yet handled by the venus-influx-loader:

The MQTT message fom the Cerbo GX is:

`N/c0619ab2f10b/system/0/Batteries {"value":[{"active_battery_service":true,"current":-10.699999809265137,"id":"com.victronenergy.battery.socketcan_can1","instance":512,"name":"Pylontech battery","power":-532,"soc":74.0,"state":2,"temperature":12.399999618530273,"voltage":49.810001373291016}]}`

Looks like the list of values is not supported for now..?
Would be very cool to have this as well :)

**Comment by mman** [comment]
The example battery dashboard works well for Pylontech assuming you set it as as a Battery Monitor in Remote Console / System Setup... and then you can query it via `system/Dc/Battery/Soc.mean` see the attached pictures...

what is your exact topology? Does it work for you on VRM? Which I believe also takes the SOC from `system/Dc/Battery`...

<img width="514" alt="Screenshot 2024-12-16 at 17 13 01" src="https://github.com/user-attachments/assets/c11faad0-456d-42d5-aaa5-4cc2dfbe39a3" />

<img width="1060" alt="Screenshot 2024-12-16 at 17 11 23" src="https://github.com/user-attachments/assets/d3e4ec4d-9a26-43e7-a156-77977d02614f" />

**Comment by maurerle** [comment]
Thanks for your Quick Answer!
I will check in the following days on vrm, as I do not have the account for it at hand.

We have Multiplus 3000, Cerbo GX, and 5 Smart Solar MPTT Charge controller and the pylontech battery..

This is my current setting:
![Screenshot From 2024-12-16 17-24-37](https://github.com/user-attachments/assets/e928b1e1-adb9-45f0-b28a-3d54f3a6ecc5)

Using `mosquitto_sub -h 192.168.2.78 -t "#" | grep -i soc` I do not see any output. So I think that my Cerbo GX is configured wrong?
Can I reboot the GX device somehow?

We can see everything in the Cerbo GX though:

![image](https://github.com/user-attachments/assets/a179c4ce-eca6-4a89-8727-3afab5333639)


![image](https://github.com/user-attachments/assets/66d36484-62e5-4f88-b9d2-afb8bd47b291)

**Comment by mman** [comment]
Your setup looks pretty standard, and config looks good as well. Could you also check the Settings / System Setup / Battery Measurements and ensure Pylontech is Enabled, and Multiplus is Disabled... that may do the trick...

The `system/Dc/Battery/Soc` topic is sent every 30 seconds unless the battery is full... but I'd verify that it looks good on VRM as well...

**Comment by maurerle** [comment]
Well.. Somehow the battery does report more like every 20 to 40 minutes..
But it works fine. Thanks for your support! :)
