### ISSUE TITLE
Bug: Fix VRM connection logic

### ISSUE THREAD

**Issue by mman** [victronenergy/venus-influx-loader#96]
Quoting @wiebeytec:

> I also see an (unused?) hostname mqtt.victronenergy.com. This works currently by accident, but is not compatible with our server sharding. See [Determining the broker URL for a given installation](https://github.com/victronenergy/dbus-flashmq?tab=readme-ov-file#determining-the-broker-url-for-a-given-installation).

> Also, it uses VRM tokens to request JWTs, but the auth scheme `Token ${app.config.secrets.vrmToken}` works with MQTT too nowadays. See [Connecting to the VRM MQTT servers](https://github.com/victronenergy/dbus-flashmq?tab=readme-ov-file#connecting-to-the-vrm-mqtt-servers). This also helps in preventing expiring JWTs.

This needs to be addressed.

**Comment by mman** [comment]
So point 1 calculating proper VRM MQTT instance is actually addressed correctly, see here:

https://github.com/victronenergy/venus-influx-loader/blob/d18ce6ebd83f98422aeaf3bd8cc788cc22a2b8f6/src/server/loader.js#L273-L280

and it works as required...

**Comment by wiebeytec** [comment]
I guess [this mention of mqtt.victronenergy.com](https://github.com/victronenergy/venus-influx-loader/blob/7a26f3eff7be67b80e1f766cc49e2e31258f7d1d/src/server/loader.js#L6) gave me the wrong impression. I guess it should be removed.
